<a href="https://colab.research.google.com/github/Karthikard/ML/blob/main/14_cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [7]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [37]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9148580968280468

In [13]:
scm=SVC()
scm.fit(X_train, y_train)
scm.score(X_test, y_test)

0.9833333333333333

In [16]:
rf=RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.975925925925926

In [23]:
#K-fold
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [28]:
#example for understanding
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [49]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)  # ✔️ Only pass X and y to .fit()
    return model.score(X_test, y_test)


In [27]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9833333333333333

In [39]:
#stratified KFold : better than kfold in seperating : uniform way
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [50]:
scores_1 = []
scores_svm = []
scores_rf = []

for train_index , test_index in kf.split(digits.data):
  X_train,X_test ,y_train,y_test=  digits.data[train_index], digits.data[test_index],\
                                    digits.target[train_index], digits.target[test_index]

  scores_1.append(get_score(LogisticRegression(max_iter=200),X_train,X_test,y_train,y_test))

  scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))

  scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))

In [51]:
scores_1

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [52]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [53]:
scores_rf

[0.9315525876460768, 0.9565943238731218, 0.9232053422370617]

from above take avg frm 3 and find the best model

In [55]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=1000),digits.data,digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [56]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [59]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target)

array([0.90555556, 0.81388889, 0.89415042, 0.90250696, 0.83286908])

In [61]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target)

array([0.93333333, 0.93055556, 0.9637883 , 0.97214485, 0.9275766 ])