<a href="https://colab.research.google.com/github/Karthikard/ML/blob/main/15_cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()

In [4]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [17]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [16]:
#Logistic Regression
l_score = cross_val_score(LogisticRegression(max_iter=1000),iris.data,iris.target)
l_score

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [18]:
np.average(l_score)

np.float64(0.9733333333333334)

In [19]:
#Decision Tree
d_score = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
d_score

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [20]:
np.average(d_score)

np.float64(0.9600000000000002)

In [22]:
#Support vector machine
s_score =cross_val_score(SVC(),iris.data,iris.target)
s_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [24]:
np.average(s_score)

np.float64(0.9666666666666666)

In [25]:
#Ramdom Forest
r_score = cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target)
r_score

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [26]:
np.average(r_score)

np.float64(0.9666666666666668)